### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Karan326** [jatzuk/MVVM-Running#1]
Sir I am also making a running tracker app, but got this error 2 days back and couldnt able to solve it yet, so could you please help

error is in inflating class google android material bottom navigation
I tried stackoverflow, youtube, but it didnt work

**Comment by jatzuk** [comment]
My pleasure. Could you provide a stack trace to clarify your error? Are you trying to implement bottom navigation from this repo?

**Comment by Karan326** [comment]
Here is the stack trace sir

**Comment by jatzuk** [comment]
I mean, can you show error [stack trace](https://en.wikipedia.org/wiki/Stack_trace), that you getting from your IDE. 

> error is in inflating class google android material bottom navigation

Interested in a full version of it

**Comment by Karan326** [comment]
here it is sir

**Comment by jatzuk** [comment]
Sorry, I can't figure out your error case in email.
