### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Karan326** [jatzuk/MVVM-Running#2]
Hello sir, I am also making this app. I am also at this commit, but i am not getting notification after clicking Start button.
I added a Log.d(message), button is working perfectly fin, but I am not getting notification.
could you please help?

**Comment by jatzuk** [comment]
Hello sir. I suppose you using the target device with API >= 26. Starting from this version you need to create a notification channel to send notifications to the user. Check out [these docs](https://developer.android.com/training/notify-user/channels).

**Comment by Karan326** [comment]
Solved it sir, actually I didn't make vector files properly.
But thank you so much for replying
